### ISSUE TITLE
Is there a workflow for importing animated rigs/skeletons from external programs?

### ISSUE THREAD

**Issue by strazto** [JLouis-B/RedTools#6]
You document exporting animated models (mesh + rig + animations) - I'm wondering if there's an inverse process -
I'd like to export a skeleton / animation, modify it externally, and then import it back into a Witcher 3 mod.

I'm uncertain if this is possible, I've found modding documentation for animations very sparse/fragmented.

**Comment by JLouis-B** [comment]
Hello,
To import mesh into The Witcher 3, my software allows the export of .re (Asset Redengine) files ([as explained here](https://github.com/JLouis-B/RedTools/wiki/How-to-import-a-3D-model-in-the-Redkit-from-a-3D-software-%3F)) that can be used with either the Redkit (The Witcher 2) or the Modkit (The Witcher 3).
The problem is that the format allows to import bones, but not skeletons (hierarchy between bones) nor animations.
For The Witcher 2, the import of these data into the engine is done through Havok files, for The Witcher 3 I don't know.

The other solution would be to directly generate w2mesh, w2anim, w2skeleton files... but these file formats are much more complex and have too many unknowns for me to generate them correctly.

So unfortunately it's going to be complicated.
In theory, what should work would be to export a .re with bones and to use an existing skeleton and animations compatible with the bones in the mesh (and it hasn't been tested much yet), but importing a custom skeleton or animation is impossible with my software.

**Comment by strazto** [comment]
Okay - I've found tools that are able to work with animations https://github.com/dingdio/witcher3-maya-animation and wolvenkit
